Section "Device"
	Identifier "AMD"
	Driver "amdgpu"
	Option "DRI" "3"
	# Using TearFree as "on" crashes system on X session logout
	Option "TearFree" "auto"
	Option "Accel" "on"
	Option "AccelMethod" "glamor"
	#Option "ShadowPrimary" "on"
EndSection
